### ISSUE TITLE
When archiving a goal, Can we handle the resetting of related tasks in the backend? cause it is currently not being handled.

### ISSUE THREAD

**Issue by Tshimangadzo** [Moses-Shilenge/Geeks4Learning#61]
When archiving a goal, Can we handle the resetting of related tasks in the backend? cause it is currently not being handled.

**Comment by Tshimangadzo** [comment]
@nhlamulo-maluleka 

Regarding this matter (Can we handle the resetting of related tasks), do we reset tasks as incomplete even if they have already been marked as complete?

**Comment by nhlamulo-maluleka** [comment]
Resolved
